{% set name = "gcc" %}
{% set version = "4.8.5" %}
{% set sha256 = "22fb1e7e0f68a63cee631d85b20461d1ea6bda162f03096350e38c8d427ecf23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: gcc-{{ version }}.tar.bz2
  url: http://www.netgull.com/gcc/releases/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    # 0001- no longer needed. GCC_PREFIX is gone (though c++ headers still in `${PREFIX}/gcc`)
    # - 0001-Libiberty-normalize-split-directories.patch
    # --print-search-dirs needs to agree with conda's library layout for various reasons.
    # One being that otherwise `-lsomelib` will not find the library in `$CONDA_PREFIX/lib`
    # An example of where this is critical is in CMake which omits the full filepath when it
    # assumes the compiler will find it without that. This is *also* a bug in CMake as it
    # should have asked the compiler for its real library search dirs via `--print-search-dirs`
    # instead of assuming `$PREFIX/lib`.
    - 0002-Disable-multiarch-like-suffixed-lib-dirs.patch
    # We never want local software (or Homebrew) leaking into our software.
    - 0003-Disable-usr-local.patch

build:
  detect_binary_files_with_prefix: false
  number: 0

requirements:
  build:
    - gmp 6.1.*
    - mpfr 3.1.*
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.0
    # Do not make gcc a build dependency (you will need to add it to the PATH manually)
  run:
    - gmp >=6.1.0,<7
    - mpfr >=3.1.0,<4
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.0

test:
  commands:
    - gcc --help

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
