{% set name = "gcc" %}
{% set version = "5.1.0" %}
{% set sha256 = "b7dafdf89cbb0e20333dbf5b5349319ae06e3d1a30bf3515b5488f7e89dca5ad" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: gcc-{{ version }}.tar.bz2
  url: http://www.netgull.com/gcc/releases/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - 0002-Disable-multiarch-like-suffixed-lib-dirs.patch
    # We never want local software (or Homebrew) leaking into our software.
    - 0003-Disable-usr-local.patch

build:
  detect_binary_files_with_prefix: false
  number: 0

requirements:
  build:
      # To get a more recent assembler which supports STB_GNU_UNIQUE symbols
    - binutils 2.28
    - gmp 6.1.*
    - mpfr 3.1.*
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.1
    # Do not make gcc a build dependency (you will need to add it to the PATH manually)
  run:
      # To get a more recent assembler which supports STB_GNU_UNIQUE symbols
    - binutils >=2.28
    - gmp >=6.1.0,<7
    - mpfr >=3.1.0,<4
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.1

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
