{% set name = "gcc" %}
{% set version = "4.9.4" %}
{% set sha256 = "6c11d292cd01b294f9f84c9a59c230d80e9e4a47e5c6355f046bb36d4f358092" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: gcc-{{ version }}.tar.bz2
  url: http://www.netgull.com/gcc/releases/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - 0002-Disable-multiarch-like-suffixed-lib-dirs.patch
    # We never want local software (or Homebrew) leaking into our software.
    - 0003-Disable-usr-local.patch

build:
  detect_binary_files_with_prefix: false
  number: 0

requirements:
  build:
    - gmp 6.1.*
    - mpfr 3.1.*
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.0
    # Do not make gcc a build dependency (you will need to add it to the PATH manually)
  run:
    - gmp >=6.1.0,<7
    - mpfr >=3.1.0,<4
    - mpc 1.0.*
    - isl 0.12.*
    - cloog 0.18.0

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
